apiVersion: v1
kind: Pod
metadata:
  name: alpine-user-context
spec:
  containers:
  - name: pod1
    image: alpine
    command: ["/bin/sleep","999999"]
    securityContext:
      runAsUser: 405 # guest user
