apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: webapp
      namespace: webapp
      labels:
        app: webapp
    spec:
      containers:
      - name: pod1
        image: linuxacademycontent/podofminerva:latest
        livenessProbe:
          httpGet:
            port: 8081
            path: /healthz
        readinessProbe:
          httpGet:
            path: /
            port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 30080
    nodePort: 30080
    
