apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  namespace: web
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data2

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: web
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce
 
---

apiVersion: v1
kind: Pod
metadata:
  name: data-pod
  namespace: web
spec:
  containers:
  - name: pod1
    image: busybox:1.28
    args: ['sh','-c',"echo $(date) > /tmp/data/1.log && sleep 3600"]
    volumeMounts:
    - name: temp-data
      mountPath: /tmp/data
  volumes:
  - name: temp-data
    persistentVolumeClaim:
        claimName: data-pvc

---

apiVersion: v1
kind: Pod
metadata:
  name: data-pod-2
  namespace: web
spec:
  containers:
  - name: pod2
    image: busybox:1.28
    args: ['sh','-c',"echo $(date) && sleep 3600"]
    volumeMounts:
    - name: temp-data
      mountPath: /tmp/data
  volumes:
  - name: temp-data
    persistentVolumeClaim:
      claimName: data-pvc
