apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfront-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webfront
  template:
    metadata:
      name: webfront-deploy
      labels:
        role: frontend
        app: webfront
    spec:
      containers:
      - name: pod1
        image: nginx:1.7.8
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: webfront-service
spec:
  selector:
    app: webfrot-deploy
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080

---

apiVersion: v1
kind: Pod
metadata:
  name: db-redis
spec:
  containers:
  - name: db-redis
    image: redis:latest

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
  - Ingress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-policy
spec:
  podSelector:
    matchLabels:
      role: db
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: frontend
    ports:
    - port: 6379
