apiVersion: v1
kind: ConfigMap
metadata:
  name: cm1
data:
  puppet.conf: |
    server=temp
    ca_server=temp

  time: |
    25
---

apiVersion: v1
kind: Secret
metadata:
  name: sec1
stringData:
  username: chai
  password: chai

---

apiVersion: v1
kind: Pod
metadata:
  name: cm-sec-pod
spec:
  containers:
  - name: cont1
    image: busybox:1.28
    args:
    - sleep
    - "36000"
    env:
    - name: password
      valueFrom:
        secretKeyRef:
          name: sec1
          key: password
    - name: time_interval
      valueFrom:
        configMapKeyRef:
          name: cm1
          key: time
    volumeMounts:
    - name: vol-cm
      mountPath: /tmp
    - name: vol-sec
      mountPath: /opt
  volumes:
  - name: vol-cm
    configMap:
      name: cm1
      items:
      - key: puppet.conf
        path: puppet.conf
  - name: vol-sec
    secret:
      secretName: sec1
      items:
      - key: password
        path: secret
      
      

