apiVersion: v1
kind: Pod
metadata:
  name: configmapvolume
spec:
  containers:
  - name: app-container
    image: busybox
    command: ['sh','-c',"echo easy && sleep 3600"]
    volumeMounts:
    - name: configmapvolume
      mountPath: /etc/config
  volumes:
  - name: configmapvolume
    configMap:
      name: appconfig
