apiVersion: v1
kind: Pod
metadata:
  name: configmap
spec:
  containers:
  - name: app-container
    image: busybox:1.28
    command: ['sh','-c',"echo ${VAR} & sleep 3600"]
    env:
    - name: VAR
      valueFrom:
        configMapKeyRef:
          name: appconfig
          key: app1
