apiVersion: v1
kind: Pod
metadata:
  name: configmappod2
spec:
  containers:
  - name: kk
    image: busybox
    command: [ 'sleep', '9999' ]
    volumeMounts:
    - name: config
      mountPath: /etc/config
  volumes:
  - name: config
    configMap:
      name: appconfig
