apiVersion: v1
kind: Pod
metadata:
  name: curlpod
spec:
  containers:
  - image: tutum/curl
    command: ["sleep","999999"]
    name: main
  - image: linuxacademycontent/kubectl-proxy
    name: proxy
  restartPolicy: Always