apiVersion: v1
kind: Pod
metadata:
  namespace: web
  name: curlpod
spec:
  containers:
  - name: main
    image: radial/busyboxplus:curl 
    command: ["sleep","999999"]
  - name: proxy
    image: linuxacademycontent/kubectl-proxy
  restartPolicy: Always
