apiVersion: v1
kind: Pod
metadata:
  name: custom-dns
spec:
  containers:
  - name: cont1
    image: curlimages/curl
    command: 
    - sleep
    - "3600000"
  dnsConfig:
    searches:
    - default.pod.cluster.local
    

