apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dep-test
  template:
    metadata:
      name: dep-test
      labels:
        app: dep-test
    spec:
      containers:
      - name: kk
        image: linuxacademycontent/kubeserve:v1
