apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: ds-example
spec:
  selector:
    matchLabels:
      app: ds-example
  template:
    metadata:
      labels:
        app: ds-example
    spec:
      nodeSelector:
        disk: ds-example
      containers:
      - name: nn
        image: linuxacademycontent/ssd-monitor
