apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webspace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: pod1
        image: linuxacademycontent/podofminerva
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
        readinessProbe:
          httpGet:
            path: /
            port: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: webspace
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - 
    port: 80
    nodePort: 30080
    targetPort: 80
    protocol: TCP

