apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
  namespace: webspace
spec:
  capacity:
    storage: 256Mi
  accessModes:
  - ReadWriteOnce

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: webspace
spec:
  requests:
    resources:
      storage: 256Mi
  accessModes:
  - ReadWriteOnce

---

apiVersion: v1
kind: Pod
metadata:
  name: data-pod
  namespace: webspace
spec:
  containers:
  - name: data-pod
    image: busybox:1.28
    volumeMounts:
    - name: temp-data
      mountPath: /tmp/data
  - name: data-pod2
    image: busybox:1.28
    volumeMounts:
    - name: temp-data
      mountPath: /tmp/data
  volumes:
  - name: temp-data
    persistentVolumeClaim:
      claimNme: data-pvc








