apiVersion: apps/v1
kind: Deployment
metadata:
  name: webfront-deploy
spec:
  selector:
    matchLabels:
      app: webfront
  replicas: 2
  template:
    metadata:
      labels:
        app: webfront
    spec:
      containers:
      - name: jj
        image: nginx:1.7.8
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: webfront-service
spec:
  type: NodePort
  selector:
    app: webfront
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080

---

apiVersion: v1
kind: Pod
metadata:
  name: db-redis
spec:
  containers:
  - name: hhh
    image: redis

---

apiVersion: v1
kind: Pod
metadata:
  name: db-not-labelled
spec:
  containers:
  - name: hhhhh
    image: busybox
    args:
    - sleep
    - "9999"
---

apiVersion: v1
kind: Pod
metadata:
  name: db-test
spec:
  containers:
  - name: hhh
    image: busybox
    args:
    - sleep
    - "9999"
---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
  - Ingress

---

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-policy
spec:
  podSelector:
    matchLabels:
      app: frontend
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: db
    ports:
    - port: 6379















