apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubeserve2-ingress
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - backend:
          serviceName: kubeserve2
          servicePort: 80
