apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: default-ingress
spec:
  rules:
  - http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginx-service
          servicePort: 8090
      - path: /kubeserve
        backend:
          serviceName: kubeserve-service
          servicePort: 8091

