apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      name: kubeserve
      labels:
        app: kubeserve
    spec:
      containers:
      - image: linuxacademycontent/kubeserve:v1
        name: app

---
apiVersion: v1
kind: Service
metadata:
  name: kubeserve-service
spec:
  type: NodePort
  selector:
    app: kubeserve
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080

    
