apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve-pod-with-pvc
  namespace: practice3
spec:
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      labels:
        app: kubeserve
    spec:
      containers:
      - name: ll
        image: linuxacademycontent/kubeserve:v1
        volumeMounts:
        - name: vol1
          mountPath: /opt/data
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: kubeserve-pvc

