apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeserve-pvc
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubeserve-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
