apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubeserve-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeserve-pvc
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve-app
  labels:
    app: kubeserve-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeserve-app
  template:
    metadata:
      name: kubeserve-app
      labels:
        app: kubeserve-app
    spec:
      containers:
      - name: app
        image: linuxacademycontent/kubeserve:v1
        volumeMounts:
        - mountPath: /data
          name: vol-data
      volumes:
      - name: vol-data
        persistentVolumeClaim:
          claimName: kubeserve-pvc
