apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeserve2-deployment
  template:
    metadata:
      labels:
        app: kubeserve2-deployment
    spec:
      containers:
      - name: kubeserve2-pod
        image: chadmcrowell/kubeserve2
