apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubeserve-pv
  namespace: practice3
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeserve-pvc
  namespace: practice3
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Mi
  accessModes:
  - ReadWriteOnce

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve-deployment
  namespace: practice3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeserve-dep
  template:
    metadata:
      labels:
        app: kubeserve-dep
    spec:
      containers:
      - name: 'hh'
        image: linuxacademycontent/kubeserve:v1
        volumeMounts:
        - name: vol1
          mountPath: /mnt/data
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: kubeserve-pvc
