apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifecycle
  namespace: practice3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lifecycle
  template:
    metadata:
      labels:
        app: lifecycle
    spec:
      containers:
      - image: linuxacademycontent/kubeserve:v1
        name: app
---
apiVersion: v1
kind: Service
metadata:
  name: lifecycle-service
  namespace: practice3
spec:
  type: NodePort
  selector:
    app: lifecycle
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
