apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifecycle
  labels:
    app: lifecycle
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lifecycle
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: lifecycle
      labels:
        app: lifecycle
    spec:
      containers:
      - name: cont1
        image: linuxacademycontent/kubeserve:v3
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 80
