apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - image: busybox
    name: main
    command:
    - sh
    - -c
    - 'echo "Ive had enough" > /var/tmp/termination-reason; exit 1'
    terminationMessagePath: /var/tmp/termination-reason
