apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity1
spec:
  containers:
  - name: cont1
    image: busybox:1.28
    args:
    - sleep
    - "36000"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: node
            operator: In
            values:
            - worker1
        weight: 50


---


apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity2
spec:
  containers:
  - name: cont1
    image: busybox:1.28
    args:
    - sleep
    - "36000"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node
            operator: In
            values:
            - worker2
