apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity1
spec:
  containers:
  - name: cont1
    image: busybox:1.28
    args:
    - sleep
    - "36000"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kubernetes.io/hostname=chaitanyah3683c.mylabserver.com
        weight: 100    
