apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-deploy
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 256Mi
  hostPath:
    path: /tmp

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-deploy
spec:
  storageClassName: local-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-main
  labels:
    app: deploy-main
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deploy-main
  template:
    metadata:
      name: deploy-main
      labels:
        app: deploy-main
    spec:
      containers:
      - name: cont1
        image: busybox:1.28
        args:
        - sleep
        - "36000"
        volumeMounts:
        - name: vol1
          mountPath: /opt/vol
      volumes:
      - name: vol1
        persistentVolumeClaim:
          claimName: pvc-deploy 
    