apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: practice3
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /opt/data
