apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeserve-pvc
  namespace: practice3
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage 
