apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness
spec:
  replicas: 3
  selector:
    matchLabels:
      app: readiness
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: readiness
      labels:
        app: readiness
    spec:
      containers:
      - name: app
        image: linuxacademycontent/kubeserve:v3
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 80
