apiVersion: v1
kind: Pod
metadata:
  name: readonly-pod
spec:
  containers:
  - name: pod1
    image: alpine
    command: ["/bin/sleep","99999999"]
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: vol1
      mountPath: /volume
      readOnly: false
  volumes:
  - name: vol1
    emptyDir: {}
