apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
  namespace: practice3
spec:
  containers:
  - name: resource-pod
    image: busybox
    args:
    - sleep
    - "9999"
    resources:
      requests:
        cpu: 80m
        memory: 20Mi
      limits:
        cpu: 800m
        memory: 100Mi
