apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-user
  namespace: practice3
spec:
  containers:
  - name: bb
    image: busybox
    command: ['sh','-c',"echo hello && sleep 1000"]
    env:
    - name: MM
      valueFrom:
        secretKeyRef:
          name: secret-pod
          key: cert

