apiVersion: v1
kind: Pod
metadata:
  name: secretvolumepod
spec:
  containers:
  - name: app-container
    image: busybox
    command: ['sh','-c',"echo ${VAR} && sleep 3600"]
    volumeMounts:
    - name: secretvolume
      mountPath: /etc/certs
  volumes:
  - name: secretvolume
    secret:
      secretName: appsecret
