apiVersion: v1
kind: Pod
metadata:
  name: secretpod
spec:
  containers:
  - name: app-container
    image: busybox
    command: ['sh','-c',"echo hello && sleep 3600"]
    env:
    - name: CERT
      valueFrom:
        secretKeyRef:
          name: appsecret
          key: cert
