
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /tmp
  storageClassName: local-storage

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /tmp
  storageClassName: local-storage

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /tmp
  storageClassName: local-storage

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv4
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /tmp
  storageClassName: local-storage

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-pv
  labels:
    app: stateful-pv
spec:
  replicas: 4
  serviceName: stateful-pv
  selector:
    matchLabels:
      app: stateful-pv
  template:
    metadata:
      name: stateful-pv
      labels:
        app: stateful-pv
    spec:
      containers:
      - name: cont1
        image: busybox:1.28
        args:
        - sleep
        - "36000"
        volumeMounts:
        - name: vol
          mountPath: /opt/pv
  volumeClaimTemplates:
  - metadata:
      name: vol
    spec:
      storageClassName: local-storage
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
