apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful
  labels:
    app: stateful
spec:
  serviceName: stateful
  replicas: 3
  selector:
    matchLabels:
      app: stateful
  template:
    metadata:
      name: stateful
      labels:
        app: stateful
    spec:
      containers:
      - name: kk
        image: linuxacademycontent/kubeserve:v1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: vol
          mountPath: /etc/config
  volumeClaimTemplates:
  - metadata:
      name: vol
    spec:
      storageClassName: local-storage
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Mi
    
