apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: st-1
spec:
  serviceName: "st-1"
  replicas: 3
  selector:
    matchLabels:
      app: st-1
  template:
    metadata:
      labels:
        app: st-1
    spec:
      containers:
      - name: kk
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: vol1
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: vol1
    spec:
      storageClassName: local-storage
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol1-pv
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol1-pv-2
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol1-pv-3
spec:
  storageClassName: local-storage
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
