apiVersion: v1
kind: Pod
metadata:
  name: data-pod
spec:
  containers:
  - name: data-pod
    image: busybox
    args:
    - 'sleep'
    - '9999'
    volumeMounts:
    - name: data-pod-volume
      mountPath: /etc/config
  volumes:
  - name: data-pod-volume
    persistentVolumeClaim:
      claimName: data-pod-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pod-pvc
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 256Mi
  accessModes:
  - ReadWriteOnce

---

apiVersion: v1
kind: PersistentVolume
