---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-puppet-agent
spec:
  containers:
  - name: cont1
    image: chaitanyah368/ubuntu-puppet-agent:latest
    command: ["/bin/sh"]
    args: ["-c","sleep 9999"]
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh","-c","/opt/puppetlabs/puppet/bin/puppet config set server puppetserver-svc.default.svc.cluster.local --section master && \
                      /opt/puppetlabs/puppet/bin/puppet config set certname ubuntu-puppet-agent --section master && \
                      /opt/puppetlabs/puppet/bin/puppet config set server puppetserver-svc.default.svc.cluster.local --section agent && \
                      /opt/puppetlabs/puppet/bin/puppet config set certname ubuntu-puppet-agent --section agent"]