apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weighted-busybox-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: weighted
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 80
            preference:
              matchExpressions:
              - key: availability-zone
                operator: In
                values:
                - zone1
          - weight: 20
            preference:
              matchExpressions:
              - key: shared-type
                operator: In
                values:
                - dedicated
      containers:
      - name: bb
        image: busybox
        args:
        - "sleep"
        - "1000"
        
