apiVersion: v1
kind: Pod
metadata:
  name: yamls
  namespace: practice3
spec:
  containers:
  - name: cont1
    image: busybox
    args:
    - sleep
    - "9999"
    volumeMounts:
    - name: vol
      mountPath: "/etc/config"
  - name: cont2
    image: busybox
    args:
    - sleep
    - "9999"
  volumes:
  - name: vol
    hostPath:
      path: "/home/cloud_user/practice-3"

